apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-voting-cluster
  region: east-us-1
  version: "1.26"

vpc:
  id: "vpc-04bac14fee0a54a9b"
  cidr: "10.0.0.0/16"
  subnets:
    public:
      us-east-1a: 
        id: "subnet-055adc9acd75fe809"
      us-east-1b: 
        id: "subnet-07b5d00afaaf89979"
      us-east-1c: 
        id: "subnet-0a5e7f70400f35f5e"
managedNodeGroups:
  - name: k8s-voting-nodes
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh k8s-voting-cluster
    instanceType: t3a.medium
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 20
    volumeEncrypted: true
    volumeType: gp3
    subnets:
      - us-east-1a
      - us-east-1b
      - us-east-1c
    labels: {role: dev}
    ssh:
      publicKeyName: linux
    tags:
      Env: Dev
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      withAddonPolicies:
        autoScaler: true