apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-voting-cluster
  region: us-east-1

vpc:
  id: "vpc-04bac14fee0a54a9b"
  cidr: "10.0.0.0/16"
  subnets:
    public:
      us-east-1a: { id: subnet-055adc9acd75fe809 }
      us-east-1b: { id: subnet-07b5d00afaaf89979 }
      us-east-1c: { id: subnet-0a5e7f70400f35f5e }

managedNodeGroups:
  - name: k8s-voting-nodes
    instanceType: t3a.medium
    labels: { role: builders }
    minSize: 2
    maxSize: 2
    ssh: 
      allow: true
      publicKeyName: linux
    tags:
      Name: k8s-voting-nodes